#!/usr/bin/env bash
# ==============================================================================
# UF1 Viewer – macOS Install Script
# ==============================================================================
# Installs Homebrew (if needed), Node.js, npm modules, and creates:
#   • /Applications/UF1 Viewer 2026.app   (double-clickable macOS app)
#   • ~/Desktop/UF1 Viewer 2026.app       (symlink shortcut on Desktop)
#   • shell alias  uf1  (in ~/.zshrc or ~/.bash_profile)
#
# Usage:
#   chmod +x install-mac.sh
#   ./install-mac.sh
# ==============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="UF1 Viewer 2026"
APP_BUNDLE="/Applications/${APP_NAME}.app"
DESKTOP_LINK="$HOME/Desktop/${APP_NAME}.app"
ICON_SOURCE="$SCRIPT_DIR/src/icons/windows/logo.png"
BUNDLE_ID="com.rhmhendriks.uf1viewer.2026"
BUNDLE_VERSION="2.1.0"

# ── Colours ──────────────────────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC} $*"; }
warning() { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERR]${NC}  $*"; exit 1; }
step()    { echo -e "${BLUE}[STEP]${NC} $*"; }

info "=== $APP_NAME macOS Installer ==="
info "Working directory: $SCRIPT_DIR"
echo ""

# ── 1. Verify macOS ───────────────────────────────────────────────────────────
if [[ "$(uname)" != "Darwin" ]]; then
    error "This script is for macOS only. Use install-ubuntu.sh on Linux."
fi
MACOS_VER=$(sw_vers -productVersion)
info "macOS version: $MACOS_VER"

# ── 2. Homebrew ───────────────────────────────────────────────────────────────
step "Checking for Homebrew..."
if ! command -v brew &>/dev/null; then
    info "Homebrew not found – installing..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    # Add Homebrew to PATH for Apple Silicon Macs
    [[ -f "/opt/homebrew/bin/brew" ]] && eval "$(/opt/homebrew/bin/brew shellenv)"
else
    info "Homebrew $(brew --version | head -1) already installed."
fi

# ── 3. Node.js ────────────────────────────────────────────────────────────────
step "Checking Node.js..."
if ! command -v node &>/dev/null; then
    info "Node.js not found – installing via Homebrew..."
    brew install node
else
    info "Node.js $(node --version) already installed."
fi

REQUIRED=18
ACTUAL=$(node --version | sed 's/v//' | cut -d. -f1)
if [ "$ACTUAL" -lt "$REQUIRED" ]; then
    error "Node.js >=18 required (found v${ACTUAL}). Run: brew upgrade node"
fi

# ── 4. npm dependencies ───────────────────────────────────────────────────────
step "Installing npm dependencies..."
cd "$SCRIPT_DIR"
npm install --no-audit 2>&1 | grep -v "^npm warn" | tail -8
info "npm install complete."

# ── 5. Build .app bundle ─────────────────────────────────────────────────────
step "Building $APP_NAME.app bundle..."

# 5a. Convert logo.png → AppIcon.icns
ICONSET_DIR="/tmp/UF1Viewer.iconset"
ICNS_FILE="/tmp/AppIcon.icns"
rm -rf "$ICONSET_DIR"
mkdir -p "$ICONSET_DIR"

sips -z 16 16     "$ICON_SOURCE" --out "$ICONSET_DIR/icon_16x16.png"      &>/dev/null
sips -z 32 32     "$ICON_SOURCE" --out "$ICONSET_DIR/icon_16x16@2x.png"   &>/dev/null
sips -z 32 32     "$ICON_SOURCE" --out "$ICONSET_DIR/icon_32x32.png"      &>/dev/null
sips -z 64 64     "$ICON_SOURCE" --out "$ICONSET_DIR/icon_32x32@2x.png"   &>/dev/null
sips -z 128 128   "$ICON_SOURCE" --out "$ICONSET_DIR/icon_128x128.png"    &>/dev/null
sips -z 256 256   "$ICON_SOURCE" --out "$ICONSET_DIR/icon_128x128@2x.png" &>/dev/null
sips -z 256 256   "$ICON_SOURCE" --out "$ICONSET_DIR/icon_256x256.png"    &>/dev/null
sips -z 512 512   "$ICON_SOURCE" --out "$ICONSET_DIR/icon_256x256@2x.png" &>/dev/null
sips -z 512 512   "$ICON_SOURCE" --out "$ICONSET_DIR/icon_512x512.png"    &>/dev/null
sips -z 1024 1024 "$ICON_SOURCE" --out "$ICONSET_DIR/icon_512x512@2x.png" &>/dev/null

iconutil -c icns "$ICONSET_DIR" -o "$ICNS_FILE"
rm -rf "$ICONSET_DIR"
info "Icon created: $ICNS_FILE"

# 5b. Create .app bundle directory structure
CONTENTS="$APP_BUNDLE/Contents"
MACOS_DIR="$CONTENTS/MacOS"
RESOURCES_DIR="$CONTENTS/Resources"

rm -rf "$APP_BUNDLE"
mkdir -p "$MACOS_DIR" "$RESOURCES_DIR"

# 5c. Write the launcher executable (runs electron directly, no terminal window)
LAUNCHER="$MACOS_DIR/UF1-Viewer-2026"
cat > "$LAUNCHER" << LAUNCHER_EOF
#!/usr/bin/env bash
# Launcher for UF1 Viewer 2026 – do not edit (regenerated by install-mac.sh)
SCRIPT_DIR="${SCRIPT_DIR}"
ELECTRON_BIN="\$SCRIPT_DIR/node_modules/.bin/electron"

# Ensure node/homebrew is in PATH when launched from Finder/Dock
export PATH="/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:\$PATH"

# Guard: check that npm install has been run
if [[ ! -x "\$ELECTRON_BIN" ]]; then
    osascript -e 'display alert "UF1 Viewer 2026" message "Electron not found.\nPlease run install-mac.sh again." buttons {"OK"} as critical'
    exit 1
fi

cd "\$SCRIPT_DIR"
exec "\$ELECTRON_BIN" "\$SCRIPT_DIR" 2>>/tmp/uf1-viewer-2026.log
LAUNCHER_EOF
chmod +x "$LAUNCHER"

# 5d. Copy icon into Resources
cp "$ICNS_FILE" "$RESOURCES_DIR/AppIcon.icns"

# 5e. Write Info.plist
cat > "$CONTENTS/Info.plist" << PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleDisplayName</key>
    <string>${APP_NAME}</string>
    <key>CFBundleIdentifier</key>
    <string>${BUNDLE_ID}</string>
    <key>CFBundleVersion</key>
    <string>${BUNDLE_VERSION}</string>
    <key>CFBundleShortVersionString</key>
    <string>${BUNDLE_VERSION}</string>
    <key>CFBundleExecutable</key>
    <string>UF1-Viewer-2026</string>
    <key>CFBundleIconFile</key>
    <string>AppIcon</string>
    <key>CFBundlePackageType</key>
    <string>APPL</string>
    <key>CFBundleSignature</key>
    <string>????</string>
    <key>NSHighResolutionCapable</key>
    <true/>
    <key>LSMinimumSystemVersion</key>
    <string>12.0</string>
    <key>NSRequiresAquaSystemAppearance</key>
    <false/>
</dict>
</plist>
PLIST_EOF

# 5f. Remove quarantine flag so Gatekeeper doesn't block self-built app
xattr -dr com.apple.quarantine "$APP_BUNDLE" 2>/dev/null || true

info "App bundle created: $APP_BUNDLE"

# ── 6. Desktop shortcut ───────────────────────────────────────────────────────
step "Creating Desktop shortcut..."
rm -f "$DESKTOP_LINK"
ln -s "$APP_BUNDLE" "$DESKTOP_LINK"
info "Desktop shortcut: $DESKTOP_LINK"

# ── 7. Shell alias ────────────────────────────────────────────────────────────
step "Setting up 'uf1' terminal alias..."
SHELL_RC=""
if [[ "$SHELL" == *"zsh"* ]];  then SHELL_RC="$HOME/.zshrc"; fi
if [[ "$SHELL" == *"bash"* ]]; then SHELL_RC="$HOME/.bash_profile"; fi

if [[ -n "$SHELL_RC" ]]; then
    if grep -qF "alias uf1=" "$SHELL_RC" 2>/dev/null; then
        info "Alias 'uf1' already in $SHELL_RC."
    else
        { echo ""; echo "# UF1 Viewer 2026"; echo "alias uf1='open -a \"${APP_NAME}\"'"; } >> "$SHELL_RC"
        info "Added 'uf1' alias to $SHELL_RC (opens the .app)."
    fi
fi

# ── 8. Notes ──────────────────────────────────────────────────────────────────
echo ""
info "=== Done! ==="
info ""
info "How to launch:"
info "  • Double-click 'UF1 Viewer 2026' on your Desktop or in /Applications"
info "  • Terminal: open -a 'UF1 Viewer 2026'"
info "  • Terminal alias (after reloading shell): uf1"
info "  • From project dir: npm start   or   ./run-mac.sh"
info ""
info "To add to Dock: open the app once, right-click its Dock icon → Options → Keep in Dock"
info ""
warning "MultiViewer for F1 must be running on http://localhost:10101 first."
info "Download MultiViewer at: https://multiviewer.app"
echo ""
